version: '3'

services:
    serveur:
        image: 
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3002:3000"
        depends_on: 
            - mongo-db
    mongo-db:
        image: mongo
        restart: always
        ports: 
            - "27017:27017"
        volumes: 
            - mongo-db-volume:/data/db

volumes: 
    mongo-db-volume: