version: '3'

services:
    mon_application:
        image: server:1.0.0
        ports:
            - "3002:3000"
        restart: always
        depends_on: 
            - mongo
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
